### ISSUE TITLE
Bug: getDIType() in Tree.cpp

### ISSUE THREAD

**Issue by XMUsuny** [ARISTODE/program-dependence-graph#11]
Hi,
I want to use PtrSplit to generate PDG for findutils-4.7.0 but it always trigger the following error:

Stack dump:
0.	Program arguments: opt -load ~/program-dependence-graph/build/libpdg.so -pdg find.ll
1.	Running pass 'Data Dependency Graph' on module 'find.ll'.
 #0 0x00007f09c29c5001 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xd1a001)
 #1 0x00007f09c29c3140 llvm::sys::RunSignalHandlers() (/usr/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xd18140)
 #2 0x00007f09c29c5712 (/usr/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xd1a712)
 #3 0x00007f09c1a9e980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #4 0x00007f09bd913a60 pdg::Node::getDIType() const ~/program-dependence-graph/include/PDGNode.hh:52:0
 #5 0x00007f09bd93bf94 pdg::TreeNode::computeDerivedAddrVarsFromParent() ~/program-dependence-graph/src/Tree.cpp:83:0
 #6 0x00007f09bd93bd1c pdg::TreeNode::expandNode() ~/program-dependence-graph/src/Tree.cpp:46:0
 #7 0x00007f09bd93c726 pdg::Tree::build(int) ~/program-dependence-graph/src/Tree.cpp:175:0
 #8 0x00007f09bd90841d pdg::FunctionWrapper::buildFormalTreeForArgs() ~/program-dependence-graph/src/FunctionWrapper.cpp:71:0
 #9 0x00007f09bd911ba0 pdg::ProgramGraph::build(llvm::Module&) ~/program-dependence-graph/src/Graph.cpp:138:0
#10 0x00007f09bd8ff93d pdg::DataDependencyGraph::runOnModule(llvm::Module&) ~/program-dependence-graph/src/DataDependencyGraph.cpp:14:0
#11 0x00007f09c2afa208 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xe4f208)
#12 0x0000000000432707 main (/usr/lib/llvm-12/bin/opt+0x432707)
#13 0x00007f09c0d7dc87 __libc_start_main /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:344:0
#14 0x000000000041e40a _start (/usr/lib/llvm-12/bin/opt+0x41e40a)
Segmentation fault (core dumped)

codes in Tree.cpp:83:0:
`  if (grand_parent_node != nullptr && dbgutils::isStructType(*_parent_node->getDIType()) && dbgutils::isStructPointerType(*grand_parent_node->getDIType()))
`
After spliting this statement to execute, I find that the `grand_parent_node->getDIType()` code always triggers the above error. I have tested PtrSplit on sysinfo in binutils and it works well. 

Could you help me find the cause and give some advises?
Thanks~

**Comment by XMUsuny** [comment]
Well, today I try to use find.bc as input instead of find.ll, which is compiled according to [master,](https://bitbucket.org/psu_soslab/program-dependence-graph-in-llvm/src/master/) and no error triggered. But I still do not know the reason.

**Comment by ARISTODE** [comment]
Hello, the PDG assumes debugging information to work properly. 
If you compile the code with -g option (clang -emit-llvm -S -g *.cpp), the PDG construction should work properly.
Please let me know if you have other questions :)
