### ISSUE TITLE
Question about how to run

### ISSUE THREAD

**Issue by TerryMXJ** [ARISTODE/program-dependence-graph#8]
Hi all, 
Thanks for your contribution to PDG generation. But When I run this project, error occur as picture shows below. Could you help me solve this. I am new to C++...
Bests,
Terry

![image](https://user-images.githubusercontent.com/23010383/146739255-87f2970b-076c-43ff-920a-57a3038cb4b9.png)

**Comment by ARISTODE** [comment]
Hi, I think if you use the main branch, it should not bring in the SVF dependency. Also, make sure you are using LLVM 10.0.0 as that's the version we used to run this project. 
To get the script we install LLVM binaries, run **wget -O - https://apt.llvm.org/llvm.sh**
Then, run **bash llvm.sh 10** to install LLVM 10.0.0.

If you want to use 12.0.0 instead, you need to fix a header missing in the project. See issue #9

**Comment by TerryMXJ** [comment]
I had fixed the header missing when I built the project. Maybe I need to install SVF first. Thanks for your suggestion.
